#+PROPERTY: header-args :dir ..
#+PROPERTY: header-args:python :session meter-classes

Analyze meter classes present in the dataset. Selected meter classes are used in model training.

#+begin_src python :results output
  from collections import Counter
  from itertools import islice
  from dataclasses import dataclass

  from velimir.domain_models import Poem, MeterType
  from velimir.io import load_poems_from_msgpack

  poems = load_poems_from_msgpack()

  meter_class_examples = {}
  meter_class_counter = Counter()

  for poem in poems:
      for i, line in enumerate(poem.lines):
          mclass = line.to_meterclass()
          meter_class_counter[mclass] += 1

          if mclass not in meter_class_examples: 
              meter_class_examples[mclass] = (poem.path, i)

  print(f"Total of {meter_class_counter.total()} lines analyzed")
  print(f"{len(meter_class_counter)} meter classes identified")
#+end_src

#+RESULTS:
: Total of 2869064 lines analyzed
: 195 meter classes identified

#+begin_src python :results graphics file value :file notebooks/coverage_vs_threshold.svg
  import numpy as np
  import matplotlib.pyplot as plt

  # TODO
#+end_src

#+RESULTS:
[[file:coverage_vs_threshold.svg]]

#+begin_src python :results output
  MIN_COUNT = 250

  discarded = 0
  discarded_items = 0

  vocab = []

  for mclass, i in meter_class_counter.most_common():
      if i < MIN_COUNT:
          discarded += 1
          discarded_items += i
          continue

      vocab.append(mclass)

  print(f"Discarded {discarded} meter classes as too rare (represent {discarded_items} lines)")
  print(f"Discarded data represents {discarded_items / meter_class_counter.total()} of lines")
  print(f"Total of {len(vocab)} meter classes accepted")
#+end_src

#+RESULTS:
: Discarded 173 meter classes as too rare (represent 3132 lines)
: Discarded data represents 0.0010916452194862157 of lines
: Total of 22 meter classes accepted

Dump class vocab to a file
#+begin_src python :results output
  import json
  from dataclasses import asdict

  from velimir.settings import METER_VOCAB_PATH

  with open(METER_VOCAB_PATH, "w") as f:
      for mclass in vocab:
          entry = asdict(mclass)
          entry["count"] = meter_class_counter[mclass]
          entry["caesura"] = list(map(str, entry["caesura"]))
          json.dump(entry, f)
          f.write("\n")

  print(f"dump meter classes to {METER_VOCAB_PATH}")
#+end_src

#+RESULTS:
: dump meter classes to data/meter_vocab.jsonl

Collect examples for selected classes (RNC files are required)
#+begin_src python :results table
  from bs4 import BeautifulSoup

  from velimir.parsers import extract_lines
  from velimir.io import read_poem_xml
  from velimir.validation import meters_to_str

  examples = []

  for mclass in vocab:
      poem_path, line_id = meter_class_examples[mclass]

      poem_xml = read_poem_xml(poem_path)
      soup = BeautifulSoup(poem_xml, "xml")
      lines = list(extract_lines(soup))

      line = lines[line_id]
      caesura_repr = "-".join(map(str, mclass.caesura))

      examples.append((line.text, meters_to_str(mclass), caesura_repr or "-", poem_path, meter_class_counter[mclass]))

  examples
#+end_src

#+RESULTS:
| 袝褖械虁 胁泻褉褍谐 褋芯虁谢薪褑械胁 薪械虁 胁褉邪褖邪虁谢懈褋褜                            | 携     | -   | xix/1790-1810_poets/poets-001 | 1472270 |
| 小褌褉邪虁褕薪邪 芯虁褌褉邪褋谢褜 写薪械虁泄 薪械斜械虁褋薪褘褏,                            | 啸     | -   | xix/1790-1810_poets/poets-008 |  514430 |
| 袙 芯褋褜屑懈褋芯虁褌 胁芯 写胁邪写褑邪虁褌芯屑 谐芯写褍,                             | 袗薪    | -   | xix/1790-1810_poets/poets-111 |  210449 |
| 袩褉械虁芯斜褉邪蟹懈虁褌械谢褜 褋谢芯胁械虁褋薪芯褋褌懈 薪邪虁褕械泄 锌懈虁褕械褌, 芯斜 薪械虁泄 褉邪褋褋褍卸写邪虁褟,  | 袛泻    | -   | xix/1790-1810_poets/poets-109 |  205477 |
| 袠谐褉邪虁泄褌械, 锌芯褌芯虁泻懈, 薪邪 屑褟虁谐泻懈褏 谢褍谐邪虁褏,                         | 袗褎    | -   | xix/1790-1810_poets/poets-026 |  201526 |
| 袥械虁褌芯 锌邪谢褟虁褖械 谢械褌懈虁褌;                                        | 袛     | -   | xix/1790-1810_poets/poets-014 |  135253 |
| 袧邪 褕懈褉芯虁泻芯屑 袣邪屑械薪薪芯虁屑 屑芯褋褌褍,                                | 孝泻    | -   | xix/1790-1810_poets/poets-111 |   39623 |
| 袦褍虁蟹 斜谢邪谐芯写邪虁褌薪褘褏 褋谢邪虁胁薪褘泄 谢褞斜懈虁屑械褑, 胁谢邪写械虁褞褖懈泄 谢懈虁褉芯泄,         | 袚械泻   | -   | xix/1790-1810_poets/poets-109 |   30943 |
| 袙芯褋褋褌邪虁薪褍褌 谢懈 斜械褋褋屑褘虁褋谢械薪薪褘械 薪邪 屑褍虁写褉褘褏 懈 褋谢邪虁斜褘械 薪邪 泻褉械虁锌泻懈褏! | 袗泻    | -   | xix/1790-1810_poets/poets-290 |   15998 |
| 袘芯谐懈薪褟 屑芯褟! 褌褘 胁 褉芯褖邪褏 褋胁褟褖械虁薪薪褘褏,                         | 小     | -   | xix/volsnx/vols-033           |   10699 |
| 袩褍褋褌褜 蟹谢褘虁械 谢褞虁写懈 胁械薪械虁褑 褋锌谢械褌邪虁褞褌,                           | 携~携   | 1/2 | xix/1790-1810_poets/poets-439 |    7627 |
| 袨虁 锌懈褌邪虁褌械谢褜薪懈褑邪虁 褉械泻邪虁 袧械胁邪虁                                  | 袥     | -   | xix/1790-1810_poets/poets-162 |    5749 |
| 袦懈虁褉薪褘泄 蟹谢邪虁泻 锌芯谢械虁泄 懈虁褋褋褍褕懈虁谢邪 芯虁褋械薪褜;                         | 啸~啸   | 1/2 | xix/1790-1810_poets/poets-170 |    4966 |
| 小谢褘虁褕邪褌褜 胁 谐褍屑薪械虁 薪邪 褌芯泻褍虁 斜芯虁泄 胁 谢邪写 褑械锌芯虁胁 屑芯谢芯褌褟虁褖懈褏:        | 袛~袛   | 1/2 | xix/1790-1810_poets/poets-109 |    3738 |
| 袥械褌芯 泻褉邪虁褋薪芯械! 锌褉芯褏芯写懈虁 褋泻芯褉械泄,                             | 袗薪~袗薪 | 1/2 | xix/1790-1810_poets/poets-116 |    1957 |
| 小芯虁胁械褌 胁 褋械虁褉写褑械 胁芯虁锌懈械虁褌, 锌谢邪虁褔褍 懈虁 褉褘写邪虁褞!                     | 啸~啸   | 4/7 | xix/1790-1810_poets/psec-153  |    1833 |
| 袝虁屑褍 芯虁锌械褉邪虁褌芯褉                                              | 啸*    | -   | xix/1830/1830-255             |    1095 |
| 袟邪 蟹薪邪虁屑褟 芯褌褔懈虁蟹薪褘 谐褉褍虁写褜褞 褋褌芯褟虁褌褜!                           | 袛泻    | 1/2 | xix/1820/1820-271             |     790 |
| 小胁芯虁写邪 锌械褖械虁褉薪芯谐芯,                                          | 携*    | -   | xix/konevskoj/konev-010       |     525 |
| 孝褘虁, 褔褌芯 褋褌芯虁谢褜泻芯 泻褉邪虁褌 褌械虁褕懈谢邪 胁 卸懈虁蟹薪懈 屑械薪褟虁.                 | 袩械薪   | -   | xix/1790-1810_poets/poets-319 |     387 |
| 袨写薪懈虁 谢懈 薪械褋褔邪虁褋褌薪褘械 蟹薪邪泻芯虁屑褘 褋 褌芯斜芯虁褞,                       | 袗褎~袗褎 | 1/2 | xix/1790-1810_poets/psec-012  |     317 |
| 孝邪屑 写邪谢械虁泻芯-写邪谢械虁泻芯, 谐写械 薪邪胁懈虁褋 芯褔邪褉芯虁胁邪薪薪褘泄 谢械虁褋,             | 袗薪~袗薪 | 2/5 | xix/lochvicka/mloch-186       |     280 |
